library(DT)
library(shiny)
library(shinydashboard)
library(shinyjs)
library(readxl)
library(xlsx)
library(dplyr)
library(plotly)
library(ggplot2)
library(purrr)
library(tidyr)
library(data.table)
# load("datos.RData")


